[build]
  command = "npm install && npm run build"  # Remove --force unless absolutely needed
  publish = "dist"
  functions = "functions"  # Add if using Netlify functions

[build.environment]
  NODE_VERSION = "20.12.2"  # Match your local Node version
  NPM_FLAGS = "--legacy-peer-deps"  # Better than --force for dependency resolution